# This is an example CI/CD workflow for a web application
#
version: 2
jobs:
  # dev stage, build and run unit test
  dev_stage:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name:
          command: |
            echo "check out code complete!"
            echo "build source code ..."
            echo "build source code SUCCESS!"
            echo "run unit test ..."
            python unit_test.py
            echo "run unit test SUCCESS!"
  test_stage:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - run:
          name:
          command: |
            echo "run integration test ..."
            python int_test.py
            echo "run integration test SUCCESS!"
workflows:
  version: 2
  my-workflow:
    jobs:
      - dev_stage
      - test_stage:
          requires:
            - dev_stage
