# This is an example CI/CD workflow for a web application
#
version: 2
jobs:
  # dev stage, build and run unit test
  dev_stage:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
#      - attach_workspace:
#          at: $CIRCLE_WORKING_DIRECTORY
      - persist_to_workspace:
          root: /root
          paths:
              - $CIRCLE_WORKING_DIRECTORY
      - run:
          name:
          command: |
            echo "check out code complete!"
            echo "build source code ..."
            echo "build source code SUCCESS!"
            echo "run unit test ..."
            python unit_test.py
            echo "run unit test SUCCESS!"
          no_output_timeout: "30s"
  test_stage:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - attach_workspace:
          at: /root
      - run:
          name:
          command: |
            echo "run integration test ..."
            python int_test.py
            echo "run integration test SUCCESS!"
          no_output_timeout: "30s"
workflows:
  version: 2
  my-workflow:
    jobs:
      - dev_stage
      - test_stage:
          requires:
            - dev_stage
