# This is an example CI/CD workflow for a web application
#
version: 2
jobs:
  # dev stage, build and run unit test
  dev_stage:
    docker:
      - image: circleci/python:3.6.8
    steps:
      # -- CN --
      # 有些项目的 Git Repo 很大, 需要比较长的时间 clone 到本地.
      # 让每个 jobs 都进行 checkout 是不明智的. 目前来说, 主要有两种解决办法
      # 1. 将 checkout 的 source code 使用 ``persist_to_workspace`` 缓存起来.
      #   然后再其他 jobs 使用 ``attach_workspace`` 进行调用
      # 2.
      # -- ENG --
      - checkout
      - persist_to_workspace:
          root: .
          paths:
              - .
      - run:
          name:
          command: |
            echo "check out code complete!"
            echo "build source code ..."
            echo "build source code SUCCESS!"
            echo "run unit test ..."
            python unit_test.py
            echo "run unit test SUCCESS!"
          no_output_timeout: "30s"
  test_stage:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - attach_workspace:
          at: .
      - run:
          name:
          command: |
            echo "run integration test ..."
            python int_test.py
            echo "run integration test SUCCESS!"
          no_output_timeout: "30s"
workflows:
  version: 2
  my-workflow:
    jobs:
      - dev_stage
      - test_stage:
          requires:
            - dev_stage
